SELECT USERS.NAME, USERS.EMAIL, auth_names.AUTH_NAME
FROM (USERS INNER JOIN AUTHS
ON USERS.UNIQUE_ID = auths.UNIQUE_ID_USERS)
INNER JOIN AUTH_NAMES
ON AUTHS.UNIQUE_ID_AUTH_NAMES = AUTH_NAMES.UNIQUE_ID
WHERE NAME IN ('Teddy', 'Allen');